### ISSUE TITLE
Update copyright headers and license

### ISSUE THREAD

**Issue by JKRhb** [eclipse-thingweb/dart_wot#65]
After the repository transfer, we should update the copyright headers contained in the source files. Currently, the general structure looks like this:

https://github.com/eclipse-thingweb/dart_wot/blob/d24bcb107530811db29b0cb1323786a524c9f7bc/lib/core.dart#L1-L5

Should we change the headers to something like this:

```
// Copyright 2021(?) Contributors to the Eclipse Foundation. All rights reserved. 
// Use of this source code is governed by a BSD-style 
// license that can be found in the LICENSE file.
```

or should we (additionally) also keep the original mentioning of "The NAMIB Project Developers"?

## Tasks

- [x] #67
- [ ] Update LICENSE file
- [ ] Update license information in copyright headers

**Comment by danielpeintner** [comment]
Generally speaking I wonder whether we have to have both licenses, BSD and Eclipse like we do in node-wot with W3C and Eclipse.
Maybe we can ask guidance from Eclipse?

> or should we (additionally) also keep the original mentioning of "The NAMIB Project Developers"?

That is a good question and I think we need to check with the "NAMIB Project". Anyhow I am not a lawyer 🙈

**Comment by JKRhb** [comment]
> Generally speaking I wonder whether we have to have both licenses, BSD and Eclipse like we do in node-wot with W3C and Eclipse.
> Maybe we can ask guidance from Eclipse?

That sounds good to me :) Should we also open an issue for that at the helpdesk?

> That is a good question and I think we need to check with the "NAMIB Project". Anyhow I am not a lawyer 🙈

"The NAMIB Project Developers" involved in this case are only @falko17 and me, actually – as it was a University project, I think replacing the copyright claim *should* be fine if @falko17 is also okay with it :)

**Comment by falko17** [comment]
> "The NAMIB Project Developers" involved in this case are only @falko17 and me, actually – as it was a University project, I think replacing the copyright claim *should* be fine if @falko17 is also okay with it :)

Sure, feel free to go ahead with that :)

**Comment by danielpeintner** [comment]
> > Generally speaking I wonder whether we have to have both licenses, BSD and Eclipse like we do in node-wot with W3C and Eclipse.
> > Maybe we can ask guidance from Eclipse?
> 
> That sounds good to me :) Should we also open an issue for that at the helpdesk?

I think we should do so but let's wait for @relu91 and @egekorkan to chime in ...

**Comment by egekorkan** [comment]
So just to be sure we should involve Eclipse but afaik, the current license should be aligned with Eclipse. We can put something like `birthday-2023: NAMIB Project, `2023-now: Eclipse Thingweb`

**Comment by JKRhb** [comment]
From the discussions we had during our last meetings and considering the feedback from Eclipse, I think we can close this issue :) Feel free to reopen if you feel there is still something to be done here :)
