### ISSUE TITLE
Register verified publisher for Dart packages

### ISSUE THREAD

**Issue by JKRhb** [eclipse-thingweb/dart_wot#66]
At the moment, `dart_wot` is registered under the "verified publisher" [namib.me](https://pub.dev/publishers/namib.me/packages) on [pub.dev](https://pub.dev), Dart and Flutter's package repository. For the nearer future, it would probably be nice to also have a verified publisher for `thingweb.io`, in order to be able to publish Dart packages in an "official" manner.

**Comment by egekorkan** [comment]
Depends on https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3995

**Comment by JKRhb** [comment]
In the meantime, this issue has been resolved as Eclipse Thingweb is now a [verified publisher](https://pub.dev/publishers/thingweb.io/packages) on pub.dev :)

I've noticed though that the description on our publisher's site is a bit truncated – I will try to fix that in the upcoming days.
